### PR TITLE
Extract case sensitive

### PR DESCRIPTION
**Pull request by thomasstvr**

### CODE REVIEW

**Comment by ChrisWRWX** [comment]
Please will you make caseSensitive snake case for consistency?

**Comment by thomasstvr** [comment]
@ChrisWRWX should I also go into Wrangles-Extract-DIY and change it there as well?

**Comment by thomasstvr** [comment]
Yeah, it's been deployed for a while. I'll leave the server side and just pass it through in params as:

{'caseSensitive': case_sensitive}

This is exactly what I just did for standardize by the way.

**Comment by ChrisWRWX** [comment]
Sounds good

**Comment by thomasstvr** [comment]
Updates have been made. Pending tests

**Review by ChrisWRWX — APPROVED** [review]

**Pull request merged**
