### PR TITLE
A more succinct option for creating columns #294

### PR DESCRIPTION
**Pull request by cerdamario13**
#294 

Dictionaries can now used in the output of `create.column` for a more succinct recipe.

```yaml
- create.column:
     output:
        col2: val2
        col3: val3
```

A value can be set that applies to any not defined directly within the output

```yaml
- create.column:
     output:
        - col2: val2
        - col3
        - col4
     value: This is a test
```

### CODE REVIEW

**Comment by ChrisWRWX** [comment]
Historically there's been an option to pass a list and it randomly chooses from the values list. I think it's a little confusing though, so as part of this can you edit it so that a list just becomes a list within the created cell?

Can we make the random choice behave like the others? `<random(["one","two","three"])>`

That's probably within the test connector.

**Comment by cerdamario13** [comment]
Something like this?

```python
df = wrangles.recipe.run(
    recipe = """
    read:
      - test:
          rows: 5
          values:
            Order_List:
              - apple
              - orange
              - banana
            Random_list: random<["one", "two", "three"]>
    """
)
```

| Order_List                    | Random_list   |
|:------------------------------|:--------------|
| ['apple', 'orange', 'banana'] | three         |
| ['apple', 'orange', 'banana'] | one           |
| ['apple', 'orange', 'banana'] | three         |
| ['apple', 'orange', 'banana'] | two           |
| ['apple', 'orange', 'banana'] | two           |

**Comment by ChrisWRWX** [comment]
Yeah

**Comment by cerdamario13** [comment]
I have added the `random list ` and `order list` to the test connector and updated tests
Forgot to mention that the test connector works with the new create columns style

```yaml
- create.column
    output: 
        - col2: <int>
        - col3: regular string
```

**Comment by ChrisWRWX** [comment]
A correction on the random syntax.

Should be `<random(["one","two","three"])>` to match the style of the existing ones.

https://wrangles.io/python/connectors/test#special-inputs

Any JSON array should work within the brackets so `([1,2,3])` or `([true, false])` or `([{}, [], ...])`

**Review by ChrisWRWX — APPROVED** [review]

**Pull request merged**
